### ISSUE TITLE
'SleepAsAndroidSensor' object has no attribute 'async_get_last_sensor_data'

### ISSUE THREAD

**Issue by MyrikLD** [IATkachenko/HA-SleepAsAndroid#60]
### Home Assistant
**Version:**
**Installation method** (according to [instructions](https://www.home-assistant.io/installation/)):
[ ] Operating System
[ ] Linux VM
[X] Container
[ ] Supervised
[ ] Core
### Integration

**Installation method:**
[ ] HACS
[X] manual from release
[ ] manual from git
**Integration version:** 
**Root topic:** 
### Application settings

**topic:**
[X] I can see MQTT messages from application at MQTT-server
## How it works now?
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 750, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1003, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/sleep_as_android/sensor.py", line 108, in async_added_to_hass
    if (old_state := await self.async_get_last_sensor_data()) is not None:
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SleepAsAndroidSensor' object has no attribute 'async_get_last_sensor_data'
```
## Steps to reproduce
Maybe, because of latest version of hass, 2023.8.3
## Additional information
https://developers.home-assistant.io/docs/core/entity/sensor/#restoring-sensor-states

**Comment by Wibias** [comment]
Uhh. What was the solution? Getting the same error.

**Comment by MyrikLD** [comment]
Update to latest version @Wibias

**Comment by IATkachenko** [comment]
Versions of HA and the integration are important: the integration v2.1.0(beta) had a bug with `async_get_last_sensor_data`.
We had migrated to `RestoreSensor` in v2.2.0, but very old HA versions may not support it.

BTW: v2.2.0 works with HA 2023.8 without such issue.
