### ISSUE TITLE
Fails to start on HA version 2024.12b3

### ISSUE THREAD

**Issue by sparkydave1981** [IATkachenko/HA-SleepAsAndroid#74]
### Home Assistant
**Version:**
**Installation method** (according to [instructions](https://www.home-assistant.io/installation/)):
[ ] Operating System

### Integration

**Installation method:**
[ ] HACS

**Integration version:** 
2.3.0
### Application settings

**topic:**
[ ] I can see MQTT messages from application at MQTT-server
## Steps to reproduce
Was working under HA version 2024.12b2 but after updating to beta 3 it fails to startup
## Debug log
```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:366
integration: Sensor (documentation, issues)
First occurred: December 2, 2024 at 17:13:27 (1 occurrences)
Last logged: December 2, 2024 at 17:13:27

Error while setting up sleep_as_android platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/sleep_as_android/sensor.py", line 50, in async_setup_entry
    await instance.subscribe_root_topic(async_add_entities)
  File "/config/custom_components/sleep_as_android/__init__.py", line 292, in subscribe_root_topic
    self._subscription_state = await subscribe_2022_03(
                               ^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "/config/custom_components/sleep_as_android/__init__.py", line 262, in subscribe_2022_03
    result = subscription.async_prepare_subscribe_topics(
        hass=_hass,
        new_state=_state,
        topics=_topic,
    )
TypeError: async_prepare_subscribe_topics() got an unexpected keyword argument 'new_state'. Did you mean 'sub_state'?
```

**Comment by sparkydave1981** [comment]
Updated HA to 2024.12b4 and have the same error.

**Comment by tnt944445** [comment]
I am also getting this error after updating to 2024.12.0b5

```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:366
integration: Sensor (documentation, issues)
First occurred: 11:53:39 PM (1 occurrences)
Last logged: 11:53:39 PM

Error while setting up sleep_as_android platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/sleep_as_android/sensor.py", line 50, in async_setup_entry
    await instance.subscribe_root_topic(async_add_entities)
  File "/config/custom_components/sleep_as_android/__init__.py", line 292, in subscribe_root_topic
    self._subscription_state = await subscribe_2022_03(
                               ^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "/config/custom_components/sleep_as_android/__init__.py", line 262, in subscribe_2022_03
    result = subscription.async_prepare_subscribe_topics(
        hass=_hass,
        new_state=_state,
        topics=_topic,
    )
TypeError: async_prepare_subscribe_topics() got an unexpected keyword argument 'new_state'. Did you mean 'sub_state'?

```

**Comment by sshaikh** [comment]
Seeing this in 2024.12 release.

**Comment by retikulumx** [comment]
Same here. You can fix this by editing the file /config/custom_components/sleep_as_android/__init__.py .
1. Open the file and search for
`result = subscription.async_prepare_subscribe_topics(
    hass=_hass,
    new_state=_state,
    topics=_topic,
)`
2. Change it to
`result = subscription.async_prepare_subscribe_topics(
    hass=_hass,
    sub_state=_state,
    topics=_topic,
)`
3. Save the file
4. Restart HA

**Comment by MinchinWeb** [comment]
A pull request with the code needed to implement this fix is here --> https://github.com/tnt944445/HA-SleepAsAndroid/pull/1/files
