### ISSUE TITLE
Deprecated async_forward_entry_setup has been removed in 2025.6

### ISSUE THREAD

**Issue by jaypi95** [IATkachenko/HA-SleepAsAndroid#88]
### Home Assistant
**Version:**
**Installation method** (according to [instructions](https://www.home-assistant.io/installation/)):
[x] Operating System
[ ] Linux VM
[ ] Container
[ ] Supervised
[ ] Core
### Integration

**Installation method:**
[x] HACS
[ ] manual from release
[ ] manual from git
**Integration version:** 
v2.3.3
**Root topic:** 
### Application settings

**topic:**
[x] I can see MQTT messages from application at MQTT-server
## How it works now?
After upgrading to 2025.6 I noticed that the integration stopped working and found this error message in the logs:
```
Logger: homeassistant.config_entries
Source: config_entries.py:749
First occurred: 9:22:51 AM (1 occurrence)
Last logged: 9:22:51 AM

Error setting up entry SleepAsAndroid for sleep_as_android
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sleep_as_android/__init__.py", line 43, in async_setup_entry
    result = await hass.config_entries.async_forward_entry_setup(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?
```
Naively I just changed `async_forward_entry_setup` to `async_forward_entry_setups` but this resulted in the following log entry:

```
Logger: homeassistant.config_entries
Source: config_entries.py:749
First occurred: June 16, 2025 at 11:48:06 PM (1 occurrence)
Last logged: June 16, 2025 at 11:48:06 PM

Error setting up entry SleepAsAndroid for sleep_as_android
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sleep_as_android/__init__.py", line 43, in async_setup_entry
    result = await hass.config_entries.async_forward_entry_setups(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        config_entry, Platform.SENSOR
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2568, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1163, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1163, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1163, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  [Previous line repeated 2 more times]
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1133, in async_get_platforms
    await self.hass.async_add_import_executor_job(
        self._load_platforms, platform_names
    )
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1076, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1250, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1282, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.sleep_as_android.s'
```

## What do you expect?
It should not throw any errors :)
## Steps to reproduce
 1. Upgrade Home Assistant to 2025.6
 1. Observe that the integration won't work anymore

## Additional information

Also see this deprecation warning from last year (not a lot of info in there tbh): https://developers.home-assistant.io/blog/2024/06/12/async_forward_entry_setups/

**Comment by jaypi95** [comment]
Just for fun I decided to merge the changes from #72 into my installation and that changed the error message a bit:

```
Logger: homeassistant.config_entries
Source: config_entries.py:749
First occurred: 4:01:52 PM (1 occurrence)
Last logged: 4:01:52 PM

Error setting up entry SleepAsAndroid for sleep_as_android
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sleep_as_android/__init__.py", line 43, in async_setup_entry
    result = await hass.config_entries.async_forward_entry_setups(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        config_entry, Platform.SENSOR
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2568, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1102, in async_get_platforms
    if platform := self._get_platform_cached_or_raise(platform_name):
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1193, in _get_platform_cached_or_raise
    raise ModuleNotFoundError(
    ...<2 lines>...
    )
ModuleNotFoundError: Platform sleep_as_android.s not found
```

**Comment by jaypi95** [comment]
Nvm I see that #73 fixes that. For some reason I have been on a [fork](https://github.com/tnt944445/HA-SleepAsAndroid) of your integration. Going back to your integration fixed it. I'm going to close this issue. Sorry for the noise.
